title: ngkan.me!
email: ngkan146@gmail.com

description: I am looking for some funs, and also challenges.
  
twitter_username: ngkan146
github_username:  ngkan
linkedin_username: khanhnguyenbx

theme: minima
