title: ngkan.me!
theme: minima
description: I am looking for some funs, and also challenges.
minima:
  skin: solarized
  
twitter_username: ngkan146
github_username:  ngkan
linkedin_username: khanhnguyenbx
pinterest_username: jekyll
youtube_username: UCM_vpwFYaUc1fsBqHE4ROaA
